### ISSUE TITLE
Request - Support Storage Size In ctera_portal_plan

### ISSUE THREAD

**Issue by mgaruccio** [ctera/ctera-ansible-collections#30]
Currently the quota settings for ctera_portal_plan support all quota settings except for the actual storage allocation.  Looking for support for setting the storage quota as part of the playbook.

**Comment by saimonation** [comment]
@mgaruccio : Thanks. Added support for customizing the storage quota of a Portal subscription plan in v2.2.14

**Comment by mgaruccio** [comment]
That was exactly what I needed, thank you!!
